# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
sudo: required
dist: trusty
# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    - ls -alF /usr/bin/Xvfb
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 +extension RANDR"
    - sleep 3 # give xvfb some time to start
    - composer update
    - "wget http://selenium-release.storage.googleapis.com/3.0-beta3/selenium-server-standalone-3.0.0-beta3.jar -O selenium-server-standalone.jar && sudo mv selenium-server-standalone.jar /usr/local/bin"
    - "wget https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz -O geckodriver.tar.gz && tar -zxf geckodriver.tar.gz && sudo mv geckodriver /usr/local/bin"
    - "java  -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver  -jar /usr/local/bin/selenium-server-standalone.jar &"
    - sleep 3
    - ls -alF /usr/local/bin/geckodriver
    - ls -alF /usr/local/bin/selenium-server-standalone.jar
    - sudo whereis firefox
    - sudo netstat -natupl | grep 444
    
script:
  phpunit Facebook.php
