# see http://about.travis-ci.org/docs/user/languages/php/ for more help
language: php
sudo: required
dist: trusty
# list any PHP version you want to test against
php:
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm
env:
  - SELENIUM="http://selenium-release.storage.googleapis.com/3.0-beta3/selenium-server-standalone-3.0.0-beta3.jar" CHROMEDRIVER="https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"

  - export DISPLAY=':99'
  - Xvfb :99 -screen 0 1280x1024x16 +extension RANDR > /dev/null 2>&1 &

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 +extension RANDR"
    - composer update
    #- sudo apt-get install -y chromium-browser
    - "wget $SELENIUM -O selenium-server-standalone.jar && sudo mv selenium-server-standalone.jar /usr/local/bin"
    - "wget $CHROMEDRIVER -O chromedriver.zip && unzip chromedriver.zip && sudo mv chromedriver /usr/local/bin"
    - "java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -jar /usr/local/bin/selenium-server-standalone.jar &"
    - sleep 3
    - sudo whereis google-chrome

script:
  phpunit Facebook.php
