# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
sudo: required
dist: trusty
# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.6

install:
  - export DISPLAY=':99'
  - Xvfb :99 -screen 0 1280x1024x16 +extension RANDR > /dev/null 2>&1 &
# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 +extension RANDR"
    - export LD_LIBRARY_PATH=”/usr/local/lib/firefox/”; export PATH=”$PATH:/usr/local/bin/firefox”;
    - composer update
    - "wget http://selenium-release.storage.googleapis.com/3.0-beta3/selenium-server-standalone-3.0.0-beta3.jar -O selenium-server-standalone.jar && sudo mv selenium-server-standalone.jar /usr/local/bin"
    - "wget https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz -O geckodriver.tar.gz && tar -zxf geckodriver.tar.gz && sudo mv geckodriver /usr/local/bin"
    - "java  -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver  -jar /usr/local/bin/selenium-server-standalone.jar &"
    - sleep 3
    - sudo whereis firefox
    - sudo netstat -natupl | grep 444
    
script:
  phpunit Facebook.php
